
spring:
  application:
    name: gateway
  jmx:
    enabled: false  # JMX dose not watch Spring Boot Application
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
          handshake-timeout-millis: 10000
          close-notify-flush-timeout-millis: 3000
          close-notify-read-timeout-millis: 0

# spring boot actuator configuration
management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: '*'

server:
  ssl:
    key-alias: 1
    key-password: changeit
    key-store-password: changeit
    # JKS format cert
    #key-store: classpath:self-signed-cert.jks
    #key-store-type: JKS
    # PKCS12 format cert
    key-store: classpath:self-signed-cert.p12
    key-store-type: PKCS12