apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gateway-testing
  namespace: asc-system
  annotations:
    ingress.controller.type: spring-cloud-gateway
spec:
  tls:
    - hosts:
        - intern-prj1.asc-test.net
      secretName: asc-test-net
  rules:
    - host: intern-prj1.asc-test.net
      http:
        paths:
          - path: /service-1/bar
            backend:
              serviceName: service-1
              servicePort: 8080
          - path: /service-1/foo
            backend:
              serviceName: service-1
              servicePort: 8080
    - host: intern-prj2.asc-test.net
      http:
        paths:
          - path: /service-2/bar
            backend:
              serviceName: service-2
              servicePort: 8080
          - path: /service-2/foo
            backend:
              serviceName: service-2
              servicePort: 8080