apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-example
  namespace: intern-project
  annotations:
    kubernetes.io/ingress.class: gateway-ingress-controller
spec:
  tls:
    - hosts:
        - foo.asc-test.net
      secretName: asc-test-net
  rules:
    - host: bar.svc.asc-test.net
      http:
        paths:
          - path: /anything/bar
            backend:
              serviceName: simple-example
              servicePort: 80
          - path: /anything/svc
            backend:
              serviceName: simple-example
              servicePort: 80
    - host: foo.asc-test.net
      http:
        paths:
          - path: /anything/foo
            backend:
              serviceName: simple-example
              servicePort: 80
          - path: /anything/asc
            backend:
              serviceName: simple-example
              servicePort: 80
          - path: /anything/test
            backend:
              serviceName: simple-example
              servicePort: 80
    - http:
        paths:
          - path: /anything/default
            backend:
              serviceName: simple-example
              servicePort: 80