---
# 创建Namespace，所有的动作和资源都隔离在这个命名空间
apiVersion: v1
kind: Namespace
metadata:
  name: intern-project

---
# 创建ServiceAccount，包含一组Pod用于访问API Server，to get or update cluster state
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
  namespace: intern-project

---
# 创建ClusterRole，用于指定一组cluster级别的权限
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role
rules:
  - apiGroups: [""]
    resources: ["endpoints", "services", "pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]

---
# 创建ClusterRoleBinding，绑定who(service account) can do what(cluster role)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role
subjects:
  - kind: ServiceAccount
    name: service-account
    namespace: intern-project
